---
title: "Methods"
output: 
  html_document:
    theme: cerulean
---

### Park Access

We completed a literature review related to this project. In this literature review we reviewed [Nicholls (2001)](https://www.tandfonline.com/doi/abs/10.1080/13606710110084651) which measured accessability in two ways. In the first method, the author creates half mile radius circles around the centroid of a park to measure access. This indicates that if a residence is within a half mile circle of the middle of the park, they have access. The second method involved creating polygons of access based on roads and entrance ways of parks. In this method, access is defined if a person is within a certain walking distance (by time) from the openings of a park.

In our project we completed two measures of access based on Nicholls (2001). In the first, we created half mile circles around park centroids and looked at the percentage of residences that were covered in a half mile radius. In the second, we created polygons called "isochrones" which are shapes of a certain time threshold. In our analysis we created isochrones at the 5-, 10-, and 15-minute levels for walking, driving, and public transportation. We then calculated the percentage of residences that are covered in each of these time thresholds.

### Racial Equity in Park Access

To measure racial equity in park access we use a two-step floating catchment area (TSFCA) method to measure ratio of parks to people. Demand of parks is measured as the fraction of a given racial group in a given geography, in this case we use tracts. Supply is measured as the number of acres of parks in a given tract. This method creates a measure to compare a racial groups' access to parks in one area versus another. High values indicate high acres, but could also mean low numbers of members of a given racial group.




